package com.ppf.dao;

import com.ppf.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);
    List<Cart> selectByUserId(Integer userId);
    /**
     * 判断购物车中商品存在否
     * */
    Cart findProductByUserIdAndProduct(@Param("userId") Integer userId,@Param("productId") Integer productId);
    /**
     * 判断是否全选
     * */
    int IsChecked(@Param("user_id") Integer user_id);
    int updateByUserIdAndCount(@Param("userId") Integer userid,@Param("productId") Integer productId,@Param("count") Integer count);
    int deleteByUserIdAndCount(@Param("userId") Integer userid,@Param("productId")Integer productId);
    int updateByCheck(@Param("userId") Integer userid,@Param("productId")Integer productId);
    int upselect(@Param("userId") Integer userid,@Param("productId")Integer productId);
    int allSelect(@Param("userId") Integer userid);
    int unallSelect(@Param("userId") Integer userid);
    int get_cart_product_count(@Param("userId") Integer userid);
    List<Cart> selectChecked(@Param("userId") Integer userid);
    int clearCart(@Param("cartList")List<Cart> cartList);
}